/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated SignedSource<<a2a81165a81e377e0df242a007daeb58>>
 * generated by gentest/gentest-driver.ts from gentest/fixtures/YGFlexTest.html
 */

package yoga_test

import (
  "testing"
 "github.com/millken/yoga"
 "github.com/dnsoa/go/assert"
)
func TestFlexBasisFlexGrowColumn(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(100)
  root.SetHeight(100)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetFlexGrow(1)
  root_child0.SetFlexBasis(50)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetFlexGrow(1)
  root.InsertChild(root_child1, 1)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0.GetComputedWidth())
  assert.Equal(t, 75, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 75, root_child1.GetComputedTop())
  assert.Equal(t, 100, root_child1.GetComputedWidth())
  assert.Equal(t, 25, root_child1.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0.GetComputedWidth())
  assert.Equal(t, 75, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 75, root_child1.GetComputedTop())
  assert.Equal(t, 100, root_child1.GetComputedWidth())
  assert.Equal(t, 25, root_child1.GetComputedHeight())
  config.Destroy()
}

func TestFlexShrinkFlexGrowRow(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetFlexDirection(yoga.FlexDirectionRow)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(500)
  root.SetHeight(500)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetFlexShrink(1)
  root_child0.SetWidth(500)
  root_child0.SetHeight(100)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetFlexShrink(1)
  root_child1.SetWidth(500)
  root_child1.SetHeight(100)
  root.InsertChild(root_child1, 1)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 500, root.GetComputedWidth())
  assert.Equal(t, 500, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 250, root_child0.GetComputedWidth())
  assert.Equal(t, 100, root_child0.GetComputedHeight())

  assert.Equal(t, 250, root_child1.GetComputedLeft())
  assert.Equal(t, 0, root_child1.GetComputedTop())
  assert.Equal(t, 250, root_child1.GetComputedWidth())
  assert.Equal(t, 100, root_child1.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 500, root.GetComputedWidth())
  assert.Equal(t, 500, root.GetComputedHeight())

  assert.Equal(t, 250, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 250, root_child0.GetComputedWidth())
  assert.Equal(t, 100, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 0, root_child1.GetComputedTop())
  assert.Equal(t, 250, root_child1.GetComputedWidth())
  assert.Equal(t, 100, root_child1.GetComputedHeight())
  config.Destroy()
}

func TestFlexShrinkFlexGrowChildFlexShrinkOtherChild(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetFlexDirection(yoga.FlexDirectionRow)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(500)
  root.SetHeight(500)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetFlexShrink(1)
  root_child0.SetWidth(500)
  root_child0.SetHeight(100)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetFlexGrow(1)
  root_child1.SetFlexShrink(1)
  root_child1.SetWidth(500)
  root_child1.SetHeight(100)
  root.InsertChild(root_child1, 1)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 500, root.GetComputedWidth())
  assert.Equal(t, 500, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 250, root_child0.GetComputedWidth())
  assert.Equal(t, 100, root_child0.GetComputedHeight())

  assert.Equal(t, 250, root_child1.GetComputedLeft())
  assert.Equal(t, 0, root_child1.GetComputedTop())
  assert.Equal(t, 250, root_child1.GetComputedWidth())
  assert.Equal(t, 100, root_child1.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 500, root.GetComputedWidth())
  assert.Equal(t, 500, root.GetComputedHeight())

  assert.Equal(t, 250, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 250, root_child0.GetComputedWidth())
  assert.Equal(t, 100, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 0, root_child1.GetComputedTop())
  assert.Equal(t, 250, root_child1.GetComputedWidth())
  assert.Equal(t, 100, root_child1.GetComputedHeight())
  config.Destroy()
}

func TestFlexBasisFlexGrowRow(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetFlexDirection(yoga.FlexDirectionRow)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(100)
  root.SetHeight(100)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetFlexGrow(1)
  root_child0.SetFlexBasis(50)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetFlexGrow(1)
  root.InsertChild(root_child1, 1)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 75, root_child0.GetComputedWidth())
  assert.Equal(t, 100, root_child0.GetComputedHeight())

  assert.Equal(t, 75, root_child1.GetComputedLeft())
  assert.Equal(t, 0, root_child1.GetComputedTop())
  assert.Equal(t, 25, root_child1.GetComputedWidth())
  assert.Equal(t, 100, root_child1.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 25, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 75, root_child0.GetComputedWidth())
  assert.Equal(t, 100, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 0, root_child1.GetComputedTop())
  assert.Equal(t, 25, root_child1.GetComputedWidth())
  assert.Equal(t, 100, root_child1.GetComputedHeight())
  config.Destroy()
}

func TestFlexBasisFlexShrinkColumn(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(100)
  root.SetHeight(100)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetFlexShrink(1)
  root_child0.SetFlexBasis(100)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetFlexBasis(50)
  root.InsertChild(root_child1, 1)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 50, root_child1.GetComputedTop())
  assert.Equal(t, 100, root_child1.GetComputedWidth())
  assert.Equal(t, 50, root_child1.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 50, root_child1.GetComputedTop())
  assert.Equal(t, 100, root_child1.GetComputedWidth())
  assert.Equal(t, 50, root_child1.GetComputedHeight())
  config.Destroy()
}

func TestFlexBasisFlexShrinkRow(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetFlexDirection(yoga.FlexDirectionRow)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(100)
  root.SetHeight(100)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetFlexShrink(1)
  root_child0.SetFlexBasis(100)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetFlexBasis(50)
  root.InsertChild(root_child1, 1)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 50, root_child0.GetComputedWidth())
  assert.Equal(t, 100, root_child0.GetComputedHeight())

  assert.Equal(t, 50, root_child1.GetComputedLeft())
  assert.Equal(t, 0, root_child1.GetComputedTop())
  assert.Equal(t, 50, root_child1.GetComputedWidth())
  assert.Equal(t, 100, root_child1.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 50, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 50, root_child0.GetComputedWidth())
  assert.Equal(t, 100, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 0, root_child1.GetComputedTop())
  assert.Equal(t, 50, root_child1.GetComputedWidth())
  assert.Equal(t, 100, root_child1.GetComputedHeight())
  config.Destroy()
}

func TestFlexShrinkToZero(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetHeight(75)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetWidth(50)
  root_child0.SetHeight(50)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetFlexShrink(1)
  root_child1.SetWidth(50)
  root_child1.SetHeight(50)
  root.InsertChild(root_child1, 1)

  root_child2 := yoga.NewNodeWithConfig(config)
  root_child2.SetWidth(50)
  root_child2.SetHeight(50)
  root.InsertChild(root_child2, 2)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 50, root.GetComputedWidth())
  assert.Equal(t, 75, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 50, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 50, root_child1.GetComputedTop())
  assert.Equal(t, 50, root_child1.GetComputedWidth())
  assert.Equal(t, 0, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 50, root_child2.GetComputedTop())
  assert.Equal(t, 50, root_child2.GetComputedWidth())
  assert.Equal(t, 50, root_child2.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 50, root.GetComputedWidth())
  assert.Equal(t, 75, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 50, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 50, root_child1.GetComputedTop())
  assert.Equal(t, 50, root_child1.GetComputedWidth())
  assert.Equal(t, 0, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 50, root_child2.GetComputedTop())
  assert.Equal(t, 50, root_child2.GetComputedWidth())
  assert.Equal(t, 50, root_child2.GetComputedHeight())
  config.Destroy()
}

func TestFlexBasisOverridesMainSize(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(100)
  root.SetHeight(100)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetFlexGrow(1)
  root_child0.SetFlexBasis(50)
  root_child0.SetHeight(20)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetFlexGrow(1)
  root_child1.SetHeight(10)
  root.InsertChild(root_child1, 1)

  root_child2 := yoga.NewNodeWithConfig(config)
  root_child2.SetFlexGrow(1)
  root_child2.SetHeight(10)
  root.InsertChild(root_child2, 2)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0.GetComputedWidth())
  assert.Equal(t, 60, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 60, root_child1.GetComputedTop())
  assert.Equal(t, 100, root_child1.GetComputedWidth())
  assert.Equal(t, 20, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 80, root_child2.GetComputedTop())
  assert.Equal(t, 100, root_child2.GetComputedWidth())
  assert.Equal(t, 20, root_child2.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0.GetComputedWidth())
  assert.Equal(t, 60, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 60, root_child1.GetComputedTop())
  assert.Equal(t, 100, root_child1.GetComputedWidth())
  assert.Equal(t, 20, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 80, root_child2.GetComputedTop())
  assert.Equal(t, 100, root_child2.GetComputedWidth())
  assert.Equal(t, 20, root_child2.GetComputedHeight())
  config.Destroy()
}

func TestFlexGrowShrinkAtMost(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(100)
  root.SetHeight(100)

  root_child0 := yoga.NewNodeWithConfig(config)
  root.InsertChild(root_child0, 0)

  root_child0_child0 := yoga.NewNodeWithConfig(config)
  root_child0_child0.SetFlexGrow(1)
  root_child0_child0.SetFlexShrink(1)
  root_child0.InsertChild(root_child0_child0, 0)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0.GetComputedWidth())
  assert.Equal(t, 0, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0_child0.GetComputedWidth())
  assert.Equal(t, 0, root_child0_child0.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0.GetComputedWidth())
  assert.Equal(t, 0, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0_child0.GetComputedWidth())
  assert.Equal(t, 0, root_child0_child0.GetComputedHeight())
  config.Destroy()
}

func TestFlexGrowLessThanFactorOne(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(200)
  root.SetHeight(500)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetFlexGrow(0.2)
  root_child0.SetFlexBasis(40)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetFlexGrow(0.2)
  root.InsertChild(root_child1, 1)

  root_child2 := yoga.NewNodeWithConfig(config)
  root_child2.SetFlexGrow(0.4)
  root.InsertChild(root_child2, 2)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 200, root.GetComputedWidth())
  assert.Equal(t, 500, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 200, root_child0.GetComputedWidth())
  assert.Equal(t, 132, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 132, root_child1.GetComputedTop())
  assert.Equal(t, 200, root_child1.GetComputedWidth())
  assert.Equal(t, 92, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 224, root_child2.GetComputedTop())
  assert.Equal(t, 200, root_child2.GetComputedWidth())
  assert.Equal(t, 184, root_child2.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 200, root.GetComputedWidth())
  assert.Equal(t, 500, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 200, root_child0.GetComputedWidth())
  assert.Equal(t, 132, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 132, root_child1.GetComputedTop())
  assert.Equal(t, 200, root_child1.GetComputedWidth())
  assert.Equal(t, 92, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 224, root_child2.GetComputedTop())
  assert.Equal(t, 200, root_child2.GetComputedWidth())
  assert.Equal(t, 184, root_child2.GetComputedHeight())
  config.Destroy()
}

