/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated SignedSource<<038918bcceb9e97f16fce1e2a1b1f624>>
 * generated by gentest/gentest-driver.ts from gentest/fixtures/YGPaddingTest.html
 */

package yoga_test

import (
  "testing"
 "github.com/millken/yoga"
 "github.com/dnsoa/go/assert"
)
func TestPaddingNoSize(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetPadding(yoga.EdgeLeft, 10)
  root.SetPadding(yoga.EdgeTop, 10)
  root.SetPadding(yoga.EdgeRight, 10)
  root.SetPadding(yoga.EdgeBottom, 10)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 20, root.GetComputedWidth())
  assert.Equal(t, 20, root.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 20, root.GetComputedWidth())
  assert.Equal(t, 20, root.GetComputedHeight())
  config.Destroy()
}

func TestPaddingContainerMatchChild(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetPadding(yoga.EdgeLeft, 10)
  root.SetPadding(yoga.EdgeTop, 10)
  root.SetPadding(yoga.EdgeRight, 10)
  root.SetPadding(yoga.EdgeBottom, 10)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetWidth(10)
  root_child0.SetHeight(10)
  root.InsertChild(root_child0, 0)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 30, root.GetComputedWidth())
  assert.Equal(t, 30, root.GetComputedHeight())

  assert.Equal(t, 10, root_child0.GetComputedLeft())
  assert.Equal(t, 10, root_child0.GetComputedTop())
  assert.Equal(t, 10, root_child0.GetComputedWidth())
  assert.Equal(t, 10, root_child0.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 30, root.GetComputedWidth())
  assert.Equal(t, 30, root.GetComputedHeight())

  assert.Equal(t, 10, root_child0.GetComputedLeft())
  assert.Equal(t, 10, root_child0.GetComputedTop())
  assert.Equal(t, 10, root_child0.GetComputedWidth())
  assert.Equal(t, 10, root_child0.GetComputedHeight())
  config.Destroy()
}

func TestPaddingFlexChild(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetPadding(yoga.EdgeLeft, 10)
  root.SetPadding(yoga.EdgeTop, 10)
  root.SetPadding(yoga.EdgeRight, 10)
  root.SetPadding(yoga.EdgeBottom, 10)
  root.SetWidth(100)
  root.SetHeight(100)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetFlexGrow(1)
  root_child0.SetWidth(10)
  root.InsertChild(root_child0, 0)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 10, root_child0.GetComputedLeft())
  assert.Equal(t, 10, root_child0.GetComputedTop())
  assert.Equal(t, 10, root_child0.GetComputedWidth())
  assert.Equal(t, 80, root_child0.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 80, root_child0.GetComputedLeft())
  assert.Equal(t, 10, root_child0.GetComputedTop())
  assert.Equal(t, 10, root_child0.GetComputedWidth())
  assert.Equal(t, 80, root_child0.GetComputedHeight())
  config.Destroy()
}

func TestPaddingStretchChild(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetPadding(yoga.EdgeLeft, 10)
  root.SetPadding(yoga.EdgeTop, 10)
  root.SetPadding(yoga.EdgeRight, 10)
  root.SetPadding(yoga.EdgeBottom, 10)
  root.SetWidth(100)
  root.SetHeight(100)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetHeight(10)
  root.InsertChild(root_child0, 0)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 10, root_child0.GetComputedLeft())
  assert.Equal(t, 10, root_child0.GetComputedTop())
  assert.Equal(t, 80, root_child0.GetComputedWidth())
  assert.Equal(t, 10, root_child0.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 10, root_child0.GetComputedLeft())
  assert.Equal(t, 10, root_child0.GetComputedTop())
  assert.Equal(t, 80, root_child0.GetComputedWidth())
  assert.Equal(t, 10, root_child0.GetComputedHeight())
  config.Destroy()
}

func TestPaddingCenterChild(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetJustifyContent(yoga.JustifyCenter)
  root.SetAlignItems(yoga.AlignCenter)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetPadding(yoga.EdgeStart, 10)
  root.SetPadding(yoga.EdgeEnd, 20)
  root.SetPadding(yoga.EdgeBottom, 20)
  root.SetWidth(100)
  root.SetHeight(100)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetWidth(10)
  root_child0.SetHeight(10)
  root.InsertChild(root_child0, 0)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 40, root_child0.GetComputedLeft())
  assert.Equal(t, 35, root_child0.GetComputedTop())
  assert.Equal(t, 10, root_child0.GetComputedWidth())
  assert.Equal(t, 10, root_child0.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 100, root.GetComputedWidth())
  assert.Equal(t, 100, root.GetComputedHeight())

  assert.Equal(t, 50, root_child0.GetComputedLeft())
  assert.Equal(t, 35, root_child0.GetComputedTop())
  assert.Equal(t, 10, root_child0.GetComputedWidth())
  assert.Equal(t, 10, root_child0.GetComputedHeight())
  config.Destroy()
}

func TestChildWithPaddingAlignEnd(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetJustifyContent(yoga.JustifyFlexEnd)
  root.SetAlignItems(yoga.AlignFlexEnd)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(200)
  root.SetHeight(200)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetPadding(yoga.EdgeLeft, 20)
  root_child0.SetPadding(yoga.EdgeTop, 20)
  root_child0.SetPadding(yoga.EdgeRight, 20)
  root_child0.SetPadding(yoga.EdgeBottom, 20)
  root_child0.SetWidth(100)
  root_child0.SetHeight(100)
  root.InsertChild(root_child0, 0)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 200, root.GetComputedWidth())
  assert.Equal(t, 200, root.GetComputedHeight())

  assert.Equal(t, 100, root_child0.GetComputedLeft())
  assert.Equal(t, 100, root_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0.GetComputedWidth())
  assert.Equal(t, 100, root_child0.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 200, root.GetComputedWidth())
  assert.Equal(t, 200, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 100, root_child0.GetComputedTop())
  assert.Equal(t, 100, root_child0.GetComputedWidth())
  assert.Equal(t, 100, root_child0.GetComputedHeight())
  config.Destroy()
}

func TestPhysicalAndRelativeEdgeDefined(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetPadding(yoga.EdgeLeft, 20)
  root.SetPadding(yoga.EdgeEnd, 50)
  root.SetWidth(200)
  root.SetHeight(200)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetWidthPercent(100)
  root_child0.SetHeight(50)
  root.InsertChild(root_child0, 0)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 200, root.GetComputedWidth())
  assert.Equal(t, 200, root.GetComputedHeight())

  assert.Equal(t, 20, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 130, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 200, root.GetComputedWidth())
  assert.Equal(t, 200, root.GetComputedHeight())

  assert.Equal(t, 50, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 150, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())
  config.Destroy()
}

