/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated SignedSource<<ad73d2c734ade7f94637f288620803d2>>
 * generated by gentest/gentest-driver.ts from gentest/fixtures/YGAlignSelfTest.html
 */

package yoga_test

import (
	"github.com/dnsoa/go/assert"
	"github.com/millken/yoga"
	"testing"
)

func TestAlignSelfCenter(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(100)
	root.SetHeight(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetAlignSelf(yoga.AlignCenter)
	root_child0.SetWidth(10)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 45, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 10, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 45, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 10, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())
	config.Destroy()
}

func TestAlignSelfFlexEnd(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(100)
	root.SetHeight(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetAlignSelf(yoga.AlignFlexEnd)
	root_child0.SetWidth(10)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 90, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 10, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 10, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())
	config.Destroy()
}

func TestAlignSelfFlexStart(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(100)
	root.SetHeight(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetAlignSelf(yoga.AlignFlexStart)
	root_child0.SetWidth(10)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 10, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 90, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 10, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())
	config.Destroy()
}

func TestAlignSelfFlexEndOverrideFlexStart(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetAlignItems(yoga.AlignFlexStart)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(100)
	root.SetHeight(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetAlignSelf(yoga.AlignFlexEnd)
	root_child0.SetWidth(10)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 90, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 10, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 10, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())
	config.Destroy()
}

func TestAlignSelfBaseline(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(100)
	root.SetHeight(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetAlignSelf(yoga.AlignBaseline)
	root_child0.SetWidth(50)
	root_child0.SetHeight(50)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetAlignSelf(yoga.AlignBaseline)
	root_child1.SetWidth(50)
	root_child1.SetHeight(20)
	root.InsertChild(root_child1, 1)

	root_child1_child0 := yoga.NewNodeWithConfig(config)
	root_child1_child0.SetWidth(50)
	root_child1_child0.SetHeight(10)
	root_child1.InsertChild(root_child1_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 50, root_child0.GetComputedWidth())
	assert.Equal(t, 50, root_child0.GetComputedHeight())

	assert.Equal(t, 50, root_child1.GetComputedLeft())
	assert.Equal(t, 40, root_child1.GetComputedTop())
	assert.Equal(t, 50, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 0, root_child1_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child1_child0.GetComputedTop())
	assert.Equal(t, 50, root_child1_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child1_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 50, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 50, root_child0.GetComputedWidth())
	assert.Equal(t, 50, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child1.GetComputedLeft())
	assert.Equal(t, 40, root_child1.GetComputedTop())
	assert.Equal(t, 50, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 0, root_child1_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child1_child0.GetComputedTop())
	assert.Equal(t, 50, root_child1_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child1_child0.GetComputedHeight())
	config.Destroy()
}
