/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated SignedSource<<d47907901510d29fc0ba136ebaf785b4>>
 * generated by gentest/gentest-driver.ts from gentest/fixtures/YGAspectRatioTest.html
 */

package yoga_test

import (
	"github.com/dnsoa/go/assert"
	"github.com/millken/yoga"
	"testing"
)

func TestAspectRatioDoesNotStretchCrossAxisDim(t *testing.T) {
	t.Skip()

	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(300)
	root.SetHeight(300)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetOverflow(yoga.OverflowScroll)
	root_child0.SetFlexGrow(1)
	root_child0.SetFlexShrink(1)
	root_child0.SetFlexBasisPercent(0)
	root.InsertChild(root_child0, 0)

	root_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0.SetFlexDirection(yoga.FlexDirectionRow)
	root_child0.InsertChild(root_child0_child0, 0)

	root_child0_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0_child0.SetFlexGrow(2)
	root_child0_child0_child0.SetFlexShrink(1)
	root_child0_child0_child0.SetFlexBasisPercent(0)
	root_child0_child0_child0.SetAspectRatio(1 / 1)
	root_child0_child0.InsertChild(root_child0_child0_child0, 0)

	root_child0_child0_child1 := yoga.NewNodeWithConfig(config)
	root_child0_child0_child1.SetWidth(5)
	root_child0_child0.InsertChild(root_child0_child0_child1, 1)

	root_child0_child0_child2 := yoga.NewNodeWithConfig(config)
	root_child0_child0_child2.SetFlexGrow(1)
	root_child0_child0_child2.SetFlexShrink(1)
	root_child0_child0_child2.SetFlexBasisPercent(0)
	root_child0_child0.InsertChild(root_child0_child0_child2, 2)

	root_child0_child0_child2_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0_child2_child0.SetFlexGrow(1)
	root_child0_child0_child2_child0.SetFlexShrink(1)
	root_child0_child0_child2_child0.SetFlexBasisPercent(0)
	root_child0_child0_child2_child0.SetAspectRatio(1 / 1)
	root_child0_child0_child2.InsertChild(root_child0_child0_child2_child0, 0)

	root_child0_child0_child2_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0_child2_child0_child0.SetWidth(5)
	root_child0_child0_child2_child0.InsertChild(root_child0_child0_child2_child0_child0, 0)

	root_child0_child0_child2_child0_child1 := yoga.NewNodeWithConfig(config)
	root_child0_child0_child2_child0_child1.SetFlexGrow(1)
	root_child0_child0_child2_child0_child1.SetFlexShrink(1)
	root_child0_child0_child2_child0_child1.SetFlexBasisPercent(0)
	root_child0_child0_child2_child0_child1.SetAspectRatio(1 / 1)
	root_child0_child0_child2_child0.InsertChild(root_child0_child0_child2_child0_child1, 1)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 300, root.GetComputedWidth())
	assert.Equal(t, 300, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 300, root_child0.GetComputedWidth())
	assert.Equal(t, 300, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 300, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child0.GetComputedTop())
	assert.Equal(t, 197, root_child0_child0_child0.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0_child0.GetComputedHeight())

	assert.Equal(t, 197, root_child0_child0_child1.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child1.GetComputedTop())
	assert.Equal(t, 5, root_child0_child0_child1.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0_child1.GetComputedHeight())

	assert.Equal(t, 202, root_child0_child0_child2.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child2.GetComputedTop())
	assert.Equal(t, 98, root_child0_child0_child2.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child2_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child2_child0.GetComputedTop())
	assert.Equal(t, 98, root_child0_child0_child2_child0.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0_child2_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child2_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child2_child0_child0.GetComputedTop())
	assert.Equal(t, 5, root_child0_child0_child2_child0_child0.GetComputedWidth())
	assert.Equal(t, 0, root_child0_child0_child2_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child2_child0_child1.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child2_child0_child1.GetComputedTop())
	assert.Equal(t, 98, root_child0_child0_child2_child0_child1.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0_child2_child0_child1.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 300, root.GetComputedWidth())
	assert.Equal(t, 300, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 300, root_child0.GetComputedWidth())
	assert.Equal(t, 300, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 300, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 103, root_child0_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child0.GetComputedTop())
	assert.Equal(t, 197, root_child0_child0_child0.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0_child0.GetComputedHeight())

	assert.Equal(t, 98, root_child0_child0_child1.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child1.GetComputedTop())
	assert.Equal(t, 5, root_child0_child0_child1.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0_child1.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child2.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child2.GetComputedTop())
	assert.Equal(t, 98, root_child0_child0_child2.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child2_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child2_child0.GetComputedTop())
	assert.Equal(t, 98, root_child0_child0_child2_child0.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0_child2_child0.GetComputedHeight())

	assert.Equal(t, 93, root_child0_child0_child2_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child2_child0_child0.GetComputedTop())
	assert.Equal(t, 5, root_child0_child0_child2_child0_child0.GetComputedWidth())
	assert.Equal(t, 0, root_child0_child0_child2_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child2_child0_child1.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child2_child0_child1.GetComputedTop())
	assert.Equal(t, 98, root_child0_child0_child2_child0_child1.GetComputedWidth())
	assert.Equal(t, 197, root_child0_child0_child2_child0_child1.GetComputedHeight())
	config.Destroy()
}

func TestZeroAspectRatioBehavesLikeAuto(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(300)
	root.SetHeight(300)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(50)
	root_child0.SetAspectRatio(0 / 1)
	root.InsertChild(root_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 300, root.GetComputedWidth())
	assert.Equal(t, 300, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 50, root_child0.GetComputedWidth())
	assert.Equal(t, 0, root_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 300, root.GetComputedWidth())
	assert.Equal(t, 300, root.GetComputedHeight())

	assert.Equal(t, 250, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 50, root_child0.GetComputedWidth())
	assert.Equal(t, 0, root_child0.GetComputedHeight())
	config.Destroy()
}
