/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated SignedSource<<41b544e5440d6f983cd0e97d95dc3a90>>
 * generated by gentest/gentest-driver.ts from gentest/fixtures/YGAutoTest.html
 */

package yoga_test

import (
  "testing"
 "github.com/millken/yoga"
 "github.com/dnsoa/go/assert"
)

func TestAutoWidth(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetFlexDirection(yoga.FlexDirectionRow)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidthAuto()
  root.SetHeight(50)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetWidth(50)
  root_child0.SetHeight(50)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetWidth(50)
  root_child1.SetHeight(50)
  root.InsertChild(root_child1, 1)

  root_child2 := yoga.NewNodeWithConfig(config)
  root_child2.SetWidth(50)
  root_child2.SetHeight(50)
  root.InsertChild(root_child2, 2)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 150, root.GetComputedWidth())
  assert.Equal(t, 50, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 50, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  assert.Equal(t, 50, root_child1.GetComputedLeft())
  assert.Equal(t, 0, root_child1.GetComputedTop())
  assert.Equal(t, 50, root_child1.GetComputedWidth())
  assert.Equal(t, 50, root_child1.GetComputedHeight())

  assert.Equal(t, 100, root_child2.GetComputedLeft())
  assert.Equal(t, 0, root_child2.GetComputedTop())
  assert.Equal(t, 50, root_child2.GetComputedWidth())
  assert.Equal(t, 50, root_child2.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 150, root.GetComputedWidth())
  assert.Equal(t, 50, root.GetComputedHeight())

  assert.Equal(t, 100, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 50, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  assert.Equal(t, 50, root_child1.GetComputedLeft())
  assert.Equal(t, 0, root_child1.GetComputedTop())
  assert.Equal(t, 50, root_child1.GetComputedWidth())
  assert.Equal(t, 50, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 0, root_child2.GetComputedTop())
  assert.Equal(t, 50, root_child2.GetComputedWidth())
  assert.Equal(t, 50, root_child2.GetComputedHeight())
  config.Destroy()
}

func TestAutoHeight(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(50)
  root.SetHeightAuto()

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetWidth(50)
  root_child0.SetHeight(50)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetWidth(50)
  root_child1.SetHeight(50)
  root.InsertChild(root_child1, 1)

  root_child2 := yoga.NewNodeWithConfig(config)
  root_child2.SetWidth(50)
  root_child2.SetHeight(50)
  root.InsertChild(root_child2, 2)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 50, root.GetComputedWidth())
  assert.Equal(t, 150, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 50, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 50, root_child1.GetComputedTop())
  assert.Equal(t, 50, root_child1.GetComputedWidth())
  assert.Equal(t, 50, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 100, root_child2.GetComputedTop())
  assert.Equal(t, 50, root_child2.GetComputedWidth())
  assert.Equal(t, 50, root_child2.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 50, root.GetComputedWidth())
  assert.Equal(t, 150, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 50, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 50, root_child1.GetComputedTop())
  assert.Equal(t, 50, root_child1.GetComputedWidth())
  assert.Equal(t, 50, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 100, root_child2.GetComputedTop())
  assert.Equal(t, 50, root_child2.GetComputedWidth())
  assert.Equal(t, 50, root_child2.GetComputedHeight())
  config.Destroy()
}

func TestAutoFlexBasis(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(50)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetWidth(50)
  root_child0.SetHeight(50)
  root.InsertChild(root_child0, 0)

  root_child1 := yoga.NewNodeWithConfig(config)
  root_child1.SetWidth(50)
  root_child1.SetHeight(50)
  root.InsertChild(root_child1, 1)

  root_child2 := yoga.NewNodeWithConfig(config)
  root_child2.SetWidth(50)
  root_child2.SetHeight(50)
  root.InsertChild(root_child2, 2)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 50, root.GetComputedWidth())
  assert.Equal(t, 150, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 50, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 50, root_child1.GetComputedTop())
  assert.Equal(t, 50, root_child1.GetComputedWidth())
  assert.Equal(t, 50, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 100, root_child2.GetComputedTop())
  assert.Equal(t, 50, root_child2.GetComputedWidth())
  assert.Equal(t, 50, root_child2.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 50, root.GetComputedWidth())
  assert.Equal(t, 150, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 50, root_child0.GetComputedWidth())
  assert.Equal(t, 50, root_child0.GetComputedHeight())

  assert.Equal(t, 0, root_child1.GetComputedLeft())
  assert.Equal(t, 50, root_child1.GetComputedTop())
  assert.Equal(t, 50, root_child1.GetComputedWidth())
  assert.Equal(t, 50, root_child1.GetComputedHeight())

  assert.Equal(t, 0, root_child2.GetComputedLeft())
  assert.Equal(t, 100, root_child2.GetComputedTop())
  assert.Equal(t, 50, root_child2.GetComputedWidth())
  assert.Equal(t, 50, root_child2.GetComputedHeight())
  config.Destroy()
}

func TestAutoPosition(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(50)
  root.SetHeight(50)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetPositionAuto(yoga.EdgeRight)
  root_child0.SetWidth(25)
  root_child0.SetHeight(25)
  root.InsertChild(root_child0, 0)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 50, root.GetComputedWidth())
  assert.Equal(t, 50, root.GetComputedHeight())

  assert.Equal(t, 0, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 25, root_child0.GetComputedWidth())
  assert.Equal(t, 25, root_child0.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 50, root.GetComputedWidth())
  assert.Equal(t, 50, root.GetComputedHeight())

  assert.Equal(t, 25, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 25, root_child0.GetComputedWidth())
  assert.Equal(t, 25, root_child0.GetComputedHeight())
  config.Destroy()
}

func TestAutoMargin(t *testing.T) {
  config := yoga.NewConfig()

  root := yoga.NewNodeWithConfig(config)
  root.SetPositionType(yoga.PositionTypeAbsolute)
  root.SetWidth(50)
  root.SetHeight(50)

  root_child0 := yoga.NewNodeWithConfig(config)
  root_child0.SetMarginAuto(yoga.EdgeLeft)
  root_child0.SetWidth(25)
  root_child0.SetHeight(25)
  root.InsertChild(root_child0, 0)
  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 50, root.GetComputedWidth())
  assert.Equal(t, 50, root.GetComputedHeight())

  assert.Equal(t, 25, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 25, root_child0.GetComputedWidth())
  assert.Equal(t, 25, root_child0.GetComputedHeight())

  root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

  assert.Equal(t, 0, root.GetComputedLeft())
  assert.Equal(t, 0, root.GetComputedTop())
  assert.Equal(t, 50, root.GetComputedWidth())
  assert.Equal(t, 50, root.GetComputedHeight())

  assert.Equal(t, 25, root_child0.GetComputedLeft())
  assert.Equal(t, 0, root_child0.GetComputedTop())
  assert.Equal(t, 25, root_child0.GetComputedWidth())
  assert.Equal(t, 25, root_child0.GetComputedHeight())
  config.Destroy()
}

