/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated SignedSource<<fe62d727e27d0806e7efa8b40f44ffcc>>
 * generated by gentest/gentest-driver.ts from gentest/fixtures/YGDimensionTest.html
 */

package yoga_test

import (
	"github.com/dnsoa/go/assert"
	"github.com/millken/yoga"
	"testing"
)

func TestWrapChild(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(100)
	root_child0.SetHeight(100)
	root.InsertChild(root_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0.GetComputedHeight())
	config.Destroy()
}

func TestWrapGrandchild(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)

	root_child0 := yoga.NewNodeWithConfig(config)
	root.InsertChild(root_child0, 0)

	root_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0.SetWidth(100)
	root_child0_child0.SetHeight(100)
	root_child0.InsertChild(root_child0_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0_child0.GetComputedHeight())
	config.Destroy()
}
