/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated SignedSource<<fbc3a707932b8737f5969b66f073260c>>
 * generated by gentest/gentest-driver.ts from gentest/fixtures/YGFlexWrapTest.html
 */

package yoga_test

import (
	"github.com/dnsoa/go/assert"
	"github.com/millken/yoga"
	"testing"
)

func TestWrapColumn(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetHeight(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(30)
	root_child0.SetHeight(30)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(30)
	root_child1.SetHeight(30)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(30)
	root_child2.SetHeight(30)
	root.InsertChild(root_child2, 2)

	root_child3 := yoga.NewNodeWithConfig(config)
	root_child3.SetWidth(30)
	root_child3.SetHeight(30)
	root.InsertChild(root_child3, 3)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 60, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 30, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child1.GetComputedLeft())
	assert.Equal(t, 30, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 30, root_child1.GetComputedHeight())

	assert.Equal(t, 0, root_child2.GetComputedLeft())
	assert.Equal(t, 60, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 30, root_child3.GetComputedLeft())
	assert.Equal(t, 0, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 30, root_child3.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 60, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 30, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 30, root_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child1.GetComputedLeft())
	assert.Equal(t, 30, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 30, root_child1.GetComputedHeight())

	assert.Equal(t, 30, root_child2.GetComputedLeft())
	assert.Equal(t, 60, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child3.GetComputedLeft())
	assert.Equal(t, 0, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 30, root_child3.GetComputedHeight())
	config.Destroy()
}

func TestWrapRow(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetWidth(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(30)
	root_child0.SetHeight(30)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(30)
	root_child1.SetHeight(30)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(30)
	root_child2.SetHeight(30)
	root.InsertChild(root_child2, 2)

	root_child3 := yoga.NewNodeWithConfig(config)
	root_child3.SetWidth(30)
	root_child3.SetHeight(30)
	root.InsertChild(root_child3, 3)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 60, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 30, root_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child1.GetComputedLeft())
	assert.Equal(t, 0, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 30, root_child1.GetComputedHeight())

	assert.Equal(t, 60, root_child2.GetComputedLeft())
	assert.Equal(t, 0, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child3.GetComputedLeft())
	assert.Equal(t, 30, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 30, root_child3.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 60, root.GetComputedHeight())

	assert.Equal(t, 70, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 30, root_child0.GetComputedHeight())

	assert.Equal(t, 40, root_child1.GetComputedLeft())
	assert.Equal(t, 0, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 30, root_child1.GetComputedHeight())

	assert.Equal(t, 10, root_child2.GetComputedLeft())
	assert.Equal(t, 0, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 70, root_child3.GetComputedLeft())
	assert.Equal(t, 30, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 30, root_child3.GetComputedHeight())
	config.Destroy()
}

func TestWrapRowAlignItemsFlexEnd(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetAlignItems(yoga.AlignFlexEnd)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetWidth(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(30)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(30)
	root_child1.SetHeight(20)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(30)
	root_child2.SetHeight(30)
	root.InsertChild(root_child2, 2)

	root_child3 := yoga.NewNodeWithConfig(config)
	root_child3.SetWidth(30)
	root_child3.SetHeight(30)
	root.InsertChild(root_child3, 3)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 60, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 20, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child1.GetComputedLeft())
	assert.Equal(t, 10, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 60, root_child2.GetComputedLeft())
	assert.Equal(t, 0, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child3.GetComputedLeft())
	assert.Equal(t, 30, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 30, root_child3.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 60, root.GetComputedHeight())

	assert.Equal(t, 70, root_child0.GetComputedLeft())
	assert.Equal(t, 20, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 40, root_child1.GetComputedLeft())
	assert.Equal(t, 10, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 10, root_child2.GetComputedLeft())
	assert.Equal(t, 0, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 70, root_child3.GetComputedLeft())
	assert.Equal(t, 30, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 30, root_child3.GetComputedHeight())
	config.Destroy()
}

func TestWrapRowAlignItemsCenter(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetAlignItems(yoga.AlignCenter)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetWidth(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(30)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(30)
	root_child1.SetHeight(20)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(30)
	root_child2.SetHeight(30)
	root.InsertChild(root_child2, 2)

	root_child3 := yoga.NewNodeWithConfig(config)
	root_child3.SetWidth(30)
	root_child3.SetHeight(30)
	root.InsertChild(root_child3, 3)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 60, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 10, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child1.GetComputedLeft())
	assert.Equal(t, 5, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 60, root_child2.GetComputedLeft())
	assert.Equal(t, 0, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child3.GetComputedLeft())
	assert.Equal(t, 30, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 30, root_child3.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 60, root.GetComputedHeight())

	assert.Equal(t, 70, root_child0.GetComputedLeft())
	assert.Equal(t, 10, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 40, root_child1.GetComputedLeft())
	assert.Equal(t, 5, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 10, root_child2.GetComputedLeft())
	assert.Equal(t, 0, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 70, root_child3.GetComputedLeft())
	assert.Equal(t, 30, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 30, root_child3.GetComputedHeight())
	config.Destroy()
}

func TestFlexWrapChildrenWithMinMainOverridingFlexBasis(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetWidth(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetFlexBasis(50)
	root_child0.SetMinWidth(55)
	root_child0.SetHeight(50)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetFlexBasis(50)
	root_child1.SetMinWidth(55)
	root_child1.SetHeight(50)
	root.InsertChild(root_child1, 1)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 55, root_child0.GetComputedWidth())
	assert.Equal(t, 50, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child1.GetComputedLeft())
	assert.Equal(t, 50, root_child1.GetComputedTop())
	assert.Equal(t, 55, root_child1.GetComputedWidth())
	assert.Equal(t, 50, root_child1.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 45, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 55, root_child0.GetComputedWidth())
	assert.Equal(t, 50, root_child0.GetComputedHeight())

	assert.Equal(t, 45, root_child1.GetComputedLeft())
	assert.Equal(t, 50, root_child1.GetComputedTop())
	assert.Equal(t, 55, root_child1.GetComputedWidth())
	assert.Equal(t, 50, root_child1.GetComputedHeight())
	config.Destroy()
}

func TestFlexWrapWrapToChildHeight(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetFlexDirection(yoga.FlexDirectionRow)
	root_child0.SetAlignItems(yoga.AlignFlexStart)
	root_child0.SetFlexWrap(yoga.WrapWrap)
	root.InsertChild(root_child0, 0)

	root_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0.SetWidth(100)
	root_child0.InsertChild(root_child0_child0, 0)

	root_child0_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0_child0.SetWidth(100)
	root_child0_child0_child0.SetHeight(100)
	root_child0_child0.InsertChild(root_child0_child0_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(100)
	root_child1.SetHeight(100)
	root.InsertChild(root_child1, 1)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 200, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0_child0_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child1.GetComputedLeft())
	assert.Equal(t, 100, root_child1.GetComputedTop())
	assert.Equal(t, 100, root_child1.GetComputedWidth())
	assert.Equal(t, 100, root_child1.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 200, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0_child0_child0.GetComputedWidth())
	assert.Equal(t, 100, root_child0_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child1.GetComputedLeft())
	assert.Equal(t, 100, root_child1.GetComputedTop())
	assert.Equal(t, 100, root_child1.GetComputedWidth())
	assert.Equal(t, 100, root_child1.GetComputedHeight())
	config.Destroy()
}

func TestFlexWrapAlignStretchFitsOneRow(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetWidth(150)
	root.SetHeight(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(50)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(50)
	root.InsertChild(root_child1, 1)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 150, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 50, root_child0.GetComputedWidth())
	assert.Equal(t, 0, root_child0.GetComputedHeight())

	assert.Equal(t, 50, root_child1.GetComputedLeft())
	assert.Equal(t, 0, root_child1.GetComputedTop())
	assert.Equal(t, 50, root_child1.GetComputedWidth())
	assert.Equal(t, 0, root_child1.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 150, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 100, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 50, root_child0.GetComputedWidth())
	assert.Equal(t, 0, root_child0.GetComputedHeight())

	assert.Equal(t, 50, root_child1.GetComputedLeft())
	assert.Equal(t, 0, root_child1.GetComputedTop())
	assert.Equal(t, 50, root_child1.GetComputedWidth())
	assert.Equal(t, 0, root_child1.GetComputedHeight())
	config.Destroy()
}

func TestWrapReverseRowAlignContentFlexStart(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrapReverse)
	root.SetWidth(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(30)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(30)
	root_child1.SetHeight(20)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(30)
	root_child2.SetHeight(30)
	root.InsertChild(root_child2, 2)

	root_child3 := yoga.NewNodeWithConfig(config)
	root_child3.SetWidth(30)
	root_child3.SetHeight(40)
	root.InsertChild(root_child3, 3)

	root_child4 := yoga.NewNodeWithConfig(config)
	root_child4.SetWidth(30)
	root_child4.SetHeight(50)
	root.InsertChild(root_child4, 4)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 80, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 70, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child1.GetComputedLeft())
	assert.Equal(t, 60, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 60, root_child2.GetComputedLeft())
	assert.Equal(t, 50, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child3.GetComputedLeft())
	assert.Equal(t, 10, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 30, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 80, root.GetComputedHeight())

	assert.Equal(t, 70, root_child0.GetComputedLeft())
	assert.Equal(t, 70, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 40, root_child1.GetComputedLeft())
	assert.Equal(t, 60, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 10, root_child2.GetComputedLeft())
	assert.Equal(t, 50, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 70, root_child3.GetComputedLeft())
	assert.Equal(t, 10, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 40, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())
	config.Destroy()
}

func TestWrapReverseRowAlignContentCenter(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetAlignContent(yoga.AlignCenter)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrapReverse)
	root.SetWidth(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(30)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(30)
	root_child1.SetHeight(20)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(30)
	root_child2.SetHeight(30)
	root.InsertChild(root_child2, 2)

	root_child3 := yoga.NewNodeWithConfig(config)
	root_child3.SetWidth(30)
	root_child3.SetHeight(40)
	root.InsertChild(root_child3, 3)

	root_child4 := yoga.NewNodeWithConfig(config)
	root_child4.SetWidth(30)
	root_child4.SetHeight(50)
	root.InsertChild(root_child4, 4)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 80, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 70, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child1.GetComputedLeft())
	assert.Equal(t, 60, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 60, root_child2.GetComputedLeft())
	assert.Equal(t, 50, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child3.GetComputedLeft())
	assert.Equal(t, 10, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 30, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 80, root.GetComputedHeight())

	assert.Equal(t, 70, root_child0.GetComputedLeft())
	assert.Equal(t, 70, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 40, root_child1.GetComputedLeft())
	assert.Equal(t, 60, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 10, root_child2.GetComputedLeft())
	assert.Equal(t, 50, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 70, root_child3.GetComputedLeft())
	assert.Equal(t, 10, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 40, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())
	config.Destroy()
}

func TestWrapReverseRowSingleLineDifferentSize(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrapReverse)
	root.SetWidth(300)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(30)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(30)
	root_child1.SetHeight(20)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(30)
	root_child2.SetHeight(30)
	root.InsertChild(root_child2, 2)

	root_child3 := yoga.NewNodeWithConfig(config)
	root_child3.SetWidth(30)
	root_child3.SetHeight(40)
	root.InsertChild(root_child3, 3)

	root_child4 := yoga.NewNodeWithConfig(config)
	root_child4.SetWidth(30)
	root_child4.SetHeight(50)
	root.InsertChild(root_child4, 4)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 300, root.GetComputedWidth())
	assert.Equal(t, 50, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 40, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child1.GetComputedLeft())
	assert.Equal(t, 30, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 60, root_child2.GetComputedLeft())
	assert.Equal(t, 20, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 90, root_child3.GetComputedLeft())
	assert.Equal(t, 10, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 120, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 300, root.GetComputedWidth())
	assert.Equal(t, 50, root.GetComputedHeight())

	assert.Equal(t, 270, root_child0.GetComputedLeft())
	assert.Equal(t, 40, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 240, root_child1.GetComputedLeft())
	assert.Equal(t, 30, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 210, root_child2.GetComputedLeft())
	assert.Equal(t, 20, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 180, root_child3.GetComputedLeft())
	assert.Equal(t, 10, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 150, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())
	config.Destroy()
}

func TestWrapReverseRowAlignContentStretch(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetAlignContent(yoga.AlignStretch)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrapReverse)
	root.SetWidth(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(30)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(30)
	root_child1.SetHeight(20)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(30)
	root_child2.SetHeight(30)
	root.InsertChild(root_child2, 2)

	root_child3 := yoga.NewNodeWithConfig(config)
	root_child3.SetWidth(30)
	root_child3.SetHeight(40)
	root.InsertChild(root_child3, 3)

	root_child4 := yoga.NewNodeWithConfig(config)
	root_child4.SetWidth(30)
	root_child4.SetHeight(50)
	root.InsertChild(root_child4, 4)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 80, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 70, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child1.GetComputedLeft())
	assert.Equal(t, 60, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 60, root_child2.GetComputedLeft())
	assert.Equal(t, 50, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child3.GetComputedLeft())
	assert.Equal(t, 10, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 30, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 80, root.GetComputedHeight())

	assert.Equal(t, 70, root_child0.GetComputedLeft())
	assert.Equal(t, 70, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 40, root_child1.GetComputedLeft())
	assert.Equal(t, 60, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 10, root_child2.GetComputedLeft())
	assert.Equal(t, 50, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 70, root_child3.GetComputedLeft())
	assert.Equal(t, 10, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 40, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())
	config.Destroy()
}

func TestWrapReverseRowAlignContentSpaceAround(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetAlignContent(yoga.AlignSpaceAround)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrapReverse)
	root.SetWidth(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(30)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(30)
	root_child1.SetHeight(20)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(30)
	root_child2.SetHeight(30)
	root.InsertChild(root_child2, 2)

	root_child3 := yoga.NewNodeWithConfig(config)
	root_child3.SetWidth(30)
	root_child3.SetHeight(40)
	root.InsertChild(root_child3, 3)

	root_child4 := yoga.NewNodeWithConfig(config)
	root_child4.SetWidth(30)
	root_child4.SetHeight(50)
	root.InsertChild(root_child4, 4)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 80, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 70, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child1.GetComputedLeft())
	assert.Equal(t, 60, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 60, root_child2.GetComputedLeft())
	assert.Equal(t, 50, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child3.GetComputedLeft())
	assert.Equal(t, 10, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 30, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 100, root.GetComputedWidth())
	assert.Equal(t, 80, root.GetComputedHeight())

	assert.Equal(t, 70, root_child0.GetComputedLeft())
	assert.Equal(t, 70, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 40, root_child1.GetComputedLeft())
	assert.Equal(t, 60, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 10, root_child2.GetComputedLeft())
	assert.Equal(t, 50, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 70, root_child3.GetComputedLeft())
	assert.Equal(t, 10, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 40, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())
	config.Destroy()
}

func TestWrapReverseColumnFixedSize(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetAlignItems(yoga.AlignCenter)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrapReverse)
	root.SetWidth(200)
	root.SetHeight(100)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(30)
	root_child0.SetHeight(10)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(30)
	root_child1.SetHeight(20)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(30)
	root_child2.SetHeight(30)
	root.InsertChild(root_child2, 2)

	root_child3 := yoga.NewNodeWithConfig(config)
	root_child3.SetWidth(30)
	root_child3.SetHeight(40)
	root.InsertChild(root_child3, 3)

	root_child4 := yoga.NewNodeWithConfig(config)
	root_child4.SetWidth(30)
	root_child4.SetHeight(50)
	root.InsertChild(root_child4, 4)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 200, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 170, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 170, root_child1.GetComputedLeft())
	assert.Equal(t, 10, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 170, root_child2.GetComputedLeft())
	assert.Equal(t, 30, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 170, root_child3.GetComputedLeft())
	assert.Equal(t, 60, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 140, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 200, root.GetComputedWidth())
	assert.Equal(t, 100, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 30, root_child0.GetComputedWidth())
	assert.Equal(t, 10, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child1.GetComputedLeft())
	assert.Equal(t, 10, root_child1.GetComputedTop())
	assert.Equal(t, 30, root_child1.GetComputedWidth())
	assert.Equal(t, 20, root_child1.GetComputedHeight())

	assert.Equal(t, 0, root_child2.GetComputedLeft())
	assert.Equal(t, 30, root_child2.GetComputedTop())
	assert.Equal(t, 30, root_child2.GetComputedWidth())
	assert.Equal(t, 30, root_child2.GetComputedHeight())

	assert.Equal(t, 0, root_child3.GetComputedLeft())
	assert.Equal(t, 60, root_child3.GetComputedTop())
	assert.Equal(t, 30, root_child3.GetComputedWidth())
	assert.Equal(t, 40, root_child3.GetComputedHeight())

	assert.Equal(t, 30, root_child4.GetComputedLeft())
	assert.Equal(t, 0, root_child4.GetComputedTop())
	assert.Equal(t, 30, root_child4.GetComputedWidth())
	assert.Equal(t, 50, root_child4.GetComputedHeight())
	config.Destroy()
}

func TestWrappedRowWithinAlignItemsCenter(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetAlignItems(yoga.AlignCenter)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(200)
	root.SetHeight(200)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetFlexDirection(yoga.FlexDirectionRow)
	root_child0.SetFlexWrap(yoga.WrapWrap)
	root.InsertChild(root_child0, 0)

	root_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0.SetWidth(150)
	root_child0_child0.SetHeight(80)
	root_child0.InsertChild(root_child0_child0, 0)

	root_child0_child1 := yoga.NewNodeWithConfig(config)
	root_child0_child1.SetWidth(80)
	root_child0_child1.SetHeight(80)
	root_child0.InsertChild(root_child0_child1, 1)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 200, root.GetComputedWidth())
	assert.Equal(t, 200, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 200, root_child0.GetComputedWidth())
	assert.Equal(t, 160, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 150, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child1.GetComputedLeft())
	assert.Equal(t, 80, root_child0_child1.GetComputedTop())
	assert.Equal(t, 80, root_child0_child1.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child1.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 200, root.GetComputedWidth())
	assert.Equal(t, 200, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 200, root_child0.GetComputedWidth())
	assert.Equal(t, 160, root_child0.GetComputedHeight())

	assert.Equal(t, 50, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 150, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 120, root_child0_child1.GetComputedLeft())
	assert.Equal(t, 80, root_child0_child1.GetComputedTop())
	assert.Equal(t, 80, root_child0_child1.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child1.GetComputedHeight())
	config.Destroy()
}

func TestWrappedRowWithinAlignItemsFlexStart(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetAlignItems(yoga.AlignFlexStart)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(200)
	root.SetHeight(200)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetFlexDirection(yoga.FlexDirectionRow)
	root_child0.SetFlexWrap(yoga.WrapWrap)
	root.InsertChild(root_child0, 0)

	root_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0.SetWidth(150)
	root_child0_child0.SetHeight(80)
	root_child0.InsertChild(root_child0_child0, 0)

	root_child0_child1 := yoga.NewNodeWithConfig(config)
	root_child0_child1.SetWidth(80)
	root_child0_child1.SetHeight(80)
	root_child0.InsertChild(root_child0_child1, 1)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 200, root.GetComputedWidth())
	assert.Equal(t, 200, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 200, root_child0.GetComputedWidth())
	assert.Equal(t, 160, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 150, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child1.GetComputedLeft())
	assert.Equal(t, 80, root_child0_child1.GetComputedTop())
	assert.Equal(t, 80, root_child0_child1.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child1.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 200, root.GetComputedWidth())
	assert.Equal(t, 200, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 200, root_child0.GetComputedWidth())
	assert.Equal(t, 160, root_child0.GetComputedHeight())

	assert.Equal(t, 50, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 150, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 120, root_child0_child1.GetComputedLeft())
	assert.Equal(t, 80, root_child0_child1.GetComputedTop())
	assert.Equal(t, 80, root_child0_child1.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child1.GetComputedHeight())
	config.Destroy()
}

func TestWrappedRowWithinAlignItemsFlexEnd(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetAlignItems(yoga.AlignFlexEnd)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(200)
	root.SetHeight(200)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetFlexDirection(yoga.FlexDirectionRow)
	root_child0.SetFlexWrap(yoga.WrapWrap)
	root.InsertChild(root_child0, 0)

	root_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0.SetWidth(150)
	root_child0_child0.SetHeight(80)
	root_child0.InsertChild(root_child0_child0, 0)

	root_child0_child1 := yoga.NewNodeWithConfig(config)
	root_child0_child1.SetWidth(80)
	root_child0_child1.SetHeight(80)
	root_child0.InsertChild(root_child0_child1, 1)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 200, root.GetComputedWidth())
	assert.Equal(t, 200, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 200, root_child0.GetComputedWidth())
	assert.Equal(t, 160, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 150, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child1.GetComputedLeft())
	assert.Equal(t, 80, root_child0_child1.GetComputedTop())
	assert.Equal(t, 80, root_child0_child1.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child1.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 200, root.GetComputedWidth())
	assert.Equal(t, 200, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 200, root_child0.GetComputedWidth())
	assert.Equal(t, 160, root_child0.GetComputedHeight())

	assert.Equal(t, 50, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 150, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 120, root_child0_child1.GetComputedLeft())
	assert.Equal(t, 80, root_child0_child1.GetComputedTop())
	assert.Equal(t, 80, root_child0_child1.GetComputedWidth())
	assert.Equal(t, 80, root_child0_child1.GetComputedHeight())
	config.Destroy()
}

func TestWrappedColumnMaxHeight(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetJustifyContent(yoga.JustifyCenter)
	root.SetAlignContent(yoga.AlignCenter)
	root.SetAlignItems(yoga.AlignCenter)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetWidth(700)
	root.SetHeight(500)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(100)
	root_child0.SetHeight(500)
	root_child0.SetMaxHeight(200)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetMargin(yoga.EdgeLeft, 20)
	root_child1.SetMargin(yoga.EdgeTop, 20)
	root_child1.SetMargin(yoga.EdgeRight, 20)
	root_child1.SetMargin(yoga.EdgeBottom, 20)
	root_child1.SetWidth(200)
	root_child1.SetHeight(200)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(100)
	root_child2.SetHeight(100)
	root.InsertChild(root_child2, 2)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 700, root.GetComputedWidth())
	assert.Equal(t, 500, root.GetComputedHeight())

	assert.Equal(t, 250, root_child0.GetComputedLeft())
	assert.Equal(t, 30, root_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0.GetComputedWidth())
	assert.Equal(t, 200, root_child0.GetComputedHeight())

	assert.Equal(t, 200, root_child1.GetComputedLeft())
	assert.Equal(t, 250, root_child1.GetComputedTop())
	assert.Equal(t, 200, root_child1.GetComputedWidth())
	assert.Equal(t, 200, root_child1.GetComputedHeight())

	assert.Equal(t, 420, root_child2.GetComputedLeft())
	assert.Equal(t, 200, root_child2.GetComputedTop())
	assert.Equal(t, 100, root_child2.GetComputedWidth())
	assert.Equal(t, 100, root_child2.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 700, root.GetComputedWidth())
	assert.Equal(t, 500, root.GetComputedHeight())

	assert.Equal(t, 350, root_child0.GetComputedLeft())
	assert.Equal(t, 30, root_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0.GetComputedWidth())
	assert.Equal(t, 200, root_child0.GetComputedHeight())

	assert.Equal(t, 300, root_child1.GetComputedLeft())
	assert.Equal(t, 250, root_child1.GetComputedTop())
	assert.Equal(t, 200, root_child1.GetComputedWidth())
	assert.Equal(t, 200, root_child1.GetComputedHeight())

	assert.Equal(t, 180, root_child2.GetComputedLeft())
	assert.Equal(t, 200, root_child2.GetComputedTop())
	assert.Equal(t, 100, root_child2.GetComputedWidth())
	assert.Equal(t, 100, root_child2.GetComputedHeight())
	config.Destroy()
}

func TestWrappedColumnMaxHeightFlex(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetJustifyContent(yoga.JustifyCenter)
	root.SetAlignContent(yoga.AlignCenter)
	root.SetAlignItems(yoga.AlignCenter)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetWidth(700)
	root.SetHeight(500)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetFlexGrow(1)
	root_child0.SetFlexShrink(1)
	root_child0.SetFlexBasisPercent(0)
	root_child0.SetWidth(100)
	root_child0.SetHeight(500)
	root_child0.SetMaxHeight(200)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetFlexGrow(1)
	root_child1.SetFlexShrink(1)
	root_child1.SetFlexBasisPercent(0)
	root_child1.SetMargin(yoga.EdgeLeft, 20)
	root_child1.SetMargin(yoga.EdgeTop, 20)
	root_child1.SetMargin(yoga.EdgeRight, 20)
	root_child1.SetMargin(yoga.EdgeBottom, 20)
	root_child1.SetWidth(200)
	root_child1.SetHeight(200)
	root.InsertChild(root_child1, 1)

	root_child2 := yoga.NewNodeWithConfig(config)
	root_child2.SetWidth(100)
	root_child2.SetHeight(100)
	root.InsertChild(root_child2, 2)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 700, root.GetComputedWidth())
	assert.Equal(t, 500, root.GetComputedHeight())

	assert.Equal(t, 300, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0.GetComputedWidth())
	assert.Equal(t, 180, root_child0.GetComputedHeight())

	assert.Equal(t, 250, root_child1.GetComputedLeft())
	assert.Equal(t, 200, root_child1.GetComputedTop())
	assert.Equal(t, 200, root_child1.GetComputedWidth())
	assert.Equal(t, 180, root_child1.GetComputedHeight())

	assert.Equal(t, 300, root_child2.GetComputedLeft())
	assert.Equal(t, 400, root_child2.GetComputedTop())
	assert.Equal(t, 100, root_child2.GetComputedWidth())
	assert.Equal(t, 100, root_child2.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 700, root.GetComputedWidth())
	assert.Equal(t, 500, root.GetComputedHeight())

	assert.Equal(t, 300, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 100, root_child0.GetComputedWidth())
	assert.Equal(t, 180, root_child0.GetComputedHeight())

	assert.Equal(t, 250, root_child1.GetComputedLeft())
	assert.Equal(t, 200, root_child1.GetComputedTop())
	assert.Equal(t, 200, root_child1.GetComputedWidth())
	assert.Equal(t, 180, root_child1.GetComputedHeight())

	assert.Equal(t, 300, root_child2.GetComputedLeft())
	assert.Equal(t, 400, root_child2.GetComputedTop())
	assert.Equal(t, 100, root_child2.GetComputedWidth())
	assert.Equal(t, 100, root_child2.GetComputedHeight())
	config.Destroy()
}

func TestWrapNodesWithContentSizingOverflowingMargin(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(500)
	root.SetHeight(500)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetFlexDirection(yoga.FlexDirectionRow)
	root_child0.SetFlexWrap(yoga.WrapWrap)
	root_child0.SetWidth(85)
	root.InsertChild(root_child0, 0)

	root_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0.InsertChild(root_child0_child0, 0)

	root_child0_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0_child0.SetWidth(40)
	root_child0_child0_child0.SetHeight(40)
	root_child0_child0.InsertChild(root_child0_child0_child0, 0)

	root_child0_child1 := yoga.NewNodeWithConfig(config)
	root_child0_child1.SetMargin(yoga.EdgeRight, 10)
	root_child0.InsertChild(root_child0_child1, 1)

	root_child0_child1_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child1_child0.SetWidth(40)
	root_child0_child1_child0.SetHeight(40)
	root_child0_child1.InsertChild(root_child0_child1_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 500, root.GetComputedWidth())
	assert.Equal(t, 500, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 85, root_child0.GetComputedWidth())
	assert.Equal(t, 80, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child0_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child1.GetComputedLeft())
	assert.Equal(t, 40, root_child0_child1.GetComputedTop())
	assert.Equal(t, 40, root_child0_child1.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child1.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child1_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child1_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child1_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child1_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 500, root.GetComputedWidth())
	assert.Equal(t, 500, root.GetComputedHeight())

	assert.Equal(t, 415, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 85, root_child0.GetComputedWidth())
	assert.Equal(t, 80, root_child0.GetComputedHeight())

	assert.Equal(t, 45, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child0_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child0_child0.GetComputedHeight())

	assert.Equal(t, 35, root_child0_child1.GetComputedLeft())
	assert.Equal(t, 40, root_child0_child1.GetComputedTop())
	assert.Equal(t, 40, root_child0_child1.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child1.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child1_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child1_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child1_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child1_child0.GetComputedHeight())
	config.Destroy()
}

func TestWrapNodesWithContentSizingMarginCross(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetWidth(500)
	root.SetHeight(500)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetFlexDirection(yoga.FlexDirectionRow)
	root_child0.SetFlexWrap(yoga.WrapWrap)
	root_child0.SetWidth(70)
	root.InsertChild(root_child0, 0)

	root_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0.InsertChild(root_child0_child0, 0)

	root_child0_child0_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child0_child0.SetWidth(40)
	root_child0_child0_child0.SetHeight(40)
	root_child0_child0.InsertChild(root_child0_child0_child0, 0)

	root_child0_child1 := yoga.NewNodeWithConfig(config)
	root_child0_child1.SetMargin(yoga.EdgeTop, 10)
	root_child0.InsertChild(root_child0_child1, 1)

	root_child0_child1_child0 := yoga.NewNodeWithConfig(config)
	root_child0_child1_child0.SetWidth(40)
	root_child0_child1_child0.SetHeight(40)
	root_child0_child1.InsertChild(root_child0_child1_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 500, root.GetComputedWidth())
	assert.Equal(t, 500, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 70, root_child0.GetComputedWidth())
	assert.Equal(t, 90, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child0_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child1.GetComputedLeft())
	assert.Equal(t, 50, root_child0_child1.GetComputedTop())
	assert.Equal(t, 40, root_child0_child1.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child1.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child1_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child1_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child1_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child1_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 500, root.GetComputedWidth())
	assert.Equal(t, 500, root.GetComputedHeight())

	assert.Equal(t, 430, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 70, root_child0.GetComputedWidth())
	assert.Equal(t, 90, root_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child0_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child0_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child0_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child0_child0.GetComputedHeight())

	assert.Equal(t, 30, root_child0_child1.GetComputedLeft())
	assert.Equal(t, 50, root_child0_child1.GetComputedTop())
	assert.Equal(t, 40, root_child0_child1.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child1.GetComputedHeight())

	assert.Equal(t, 0, root_child0_child1_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0_child1_child0.GetComputedTop())
	assert.Equal(t, 40, root_child0_child1_child0.GetComputedWidth())
	assert.Equal(t, 40, root_child0_child1_child0.GetComputedHeight())
	config.Destroy()
}

func TestWrapWithMinCrossAxis(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetWidth(500)
	root.SetMinHeight(500)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(400)
	root_child0.SetHeight(200)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(400)
	root_child1.SetHeight(200)
	root.InsertChild(root_child1, 1)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 500, root.GetComputedWidth())
	assert.Equal(t, 500, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 400, root_child0.GetComputedWidth())
	assert.Equal(t, 200, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child1.GetComputedLeft())
	assert.Equal(t, 200, root_child1.GetComputedTop())
	assert.Equal(t, 400, root_child1.GetComputedWidth())
	assert.Equal(t, 200, root_child1.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 500, root.GetComputedWidth())
	assert.Equal(t, 500, root.GetComputedHeight())

	assert.Equal(t, 100, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 400, root_child0.GetComputedWidth())
	assert.Equal(t, 200, root_child0.GetComputedHeight())

	assert.Equal(t, 100, root_child1.GetComputedLeft())
	assert.Equal(t, 200, root_child1.GetComputedTop())
	assert.Equal(t, 400, root_child1.GetComputedWidth())
	assert.Equal(t, 200, root_child1.GetComputedHeight())
	config.Destroy()
}

func TestWrapWithMaxCrossAxis(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetWidth(500)
	root.SetMaxHeight(500)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetWidth(400)
	root_child0.SetHeight(200)
	root.InsertChild(root_child0, 0)

	root_child1 := yoga.NewNodeWithConfig(config)
	root_child1.SetWidth(400)
	root_child1.SetHeight(200)
	root.InsertChild(root_child1, 1)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 500, root.GetComputedWidth())
	assert.Equal(t, 400, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 400, root_child0.GetComputedWidth())
	assert.Equal(t, 200, root_child0.GetComputedHeight())

	assert.Equal(t, 0, root_child1.GetComputedLeft())
	assert.Equal(t, 200, root_child1.GetComputedTop())
	assert.Equal(t, 400, root_child1.GetComputedWidth())
	assert.Equal(t, 200, root_child1.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 500, root.GetComputedWidth())
	assert.Equal(t, 400, root.GetComputedHeight())

	assert.Equal(t, 100, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 400, root_child0.GetComputedWidth())
	assert.Equal(t, 200, root_child0.GetComputedHeight())

	assert.Equal(t, 100, root_child1.GetComputedLeft())
	assert.Equal(t, 200, root_child1.GetComputedTop())
	assert.Equal(t, 400, root_child1.GetComputedWidth())
	assert.Equal(t, 200, root_child1.GetComputedHeight())
	config.Destroy()
}

func TestNowrapExpandsFlexlineBoxToMinCross(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetMinHeight(400)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetFlexGrow(1)
	root_child0.SetFlexShrink(1)
	root_child0.SetFlexBasisPercent(0)
	root.InsertChild(root_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 0, root.GetComputedWidth())
	assert.Equal(t, 400, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 0, root_child0.GetComputedWidth())
	assert.Equal(t, 400, root_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 0, root.GetComputedWidth())
	assert.Equal(t, 400, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 0, root_child0.GetComputedWidth())
	assert.Equal(t, 400, root_child0.GetComputedHeight())
	config.Destroy()
}

func TestWrapDoesNotImposeMinCrossOntoSingleFlexline(t *testing.T) {
	config := yoga.NewConfig()

	root := yoga.NewNodeWithConfig(config)
	root.SetFlexDirection(yoga.FlexDirectionRow)
	root.SetPositionType(yoga.PositionTypeAbsolute)
	root.SetFlexWrap(yoga.WrapWrap)
	root.SetMinHeight(400)

	root_child0 := yoga.NewNodeWithConfig(config)
	root_child0.SetFlexGrow(1)
	root_child0.SetFlexShrink(1)
	root_child0.SetFlexBasisPercent(0)
	root.InsertChild(root_child0, 0)
	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionLTR)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 0, root.GetComputedWidth())
	assert.Equal(t, 400, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 0, root_child0.GetComputedWidth())
	assert.Equal(t, 0, root_child0.GetComputedHeight())

	root.CalculateLayout(yoga.Undefined, yoga.Undefined, yoga.DirectionRTL)

	assert.Equal(t, 0, root.GetComputedLeft())
	assert.Equal(t, 0, root.GetComputedTop())
	assert.Equal(t, 0, root.GetComputedWidth())
	assert.Equal(t, 400, root.GetComputedHeight())

	assert.Equal(t, 0, root_child0.GetComputedLeft())
	assert.Equal(t, 0, root_child0.GetComputedTop())
	assert.Equal(t, 0, root_child0.GetComputedWidth())
	assert.Equal(t, 0, root_child0.GetComputedHeight())
	config.Destroy()
}
